# Generated by Django 4.2.4 on 2023-09-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos_equip',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(db_column='id_permission', primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'permissions',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('leitura', models.CharField(max_length=1)),
                ('escrita', models.CharField(max_length=1)),
                ('edicao', models.CharField(max_length=1)),
                ('exclusao', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'grupos',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermissaoAdministrativa',
            fields=[
                ('id', models.AutoField(db_column='id_permissoes_administrativas', primary_key=True, serialize=False)),
                ('leitura', models.BooleanField()),
                ('escrita', models.BooleanField()),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.permission')),
                ('ugrupo', models.ForeignKey(db_column='grupos_id', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.ugrupo')),
            ],
            options={
                'db_table': 'permissoes_administrativas',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DireitosGrupoEquipamento',
            fields=[
                ('id', models.AutoField(db_column='id_direito', primary_key=True, serialize=False)),
                ('leitura', models.BooleanField()),
                ('escrita', models.BooleanField()),
                ('alterar_config', models.BooleanField()),
                ('exclusao', models.BooleanField()),
                ('egrupo', models.ForeignKey(db_column='id_egrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.egrupo')),
                ('ugrupo', models.ForeignKey(db_column='id_ugrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.ugrupo')),
            ],
            options={
                'db_table': 'direitos_grupoequip',
                'abstract': False,
                'managed': True,
                'unique_together': {('ugrupo', 'egrupo')},
            },
        ),
    ]
