# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(db_column='id_rule', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=80)),
                ('vip', models.IntegerField(blank=True, db_column='id_vip', null=True)),
                ('environment', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
            ],
            options={
                'db_table': 'rule',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RuleContent',
            fields=[
                ('id', models.AutoField(db_column='id_rule_content', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='content')),
                ('order', models.IntegerField(db_column='order')),
                ('rule', models.ForeignKey(db_column='id_rule', on_delete=django.db.models.deletion.CASCADE, to='blockrules.rule')),
            ],
            options={
                'db_table': 'rule_content',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlockRules',
            fields=[
                ('id', models.AutoField(db_column='id_block_rules', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='content')),
                ('order', models.IntegerField()),
                ('environment', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
            ],
            options={
                'db_table': 'block_rules',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
