# Generated by Django 4.2.4 on 2023-09-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterEquipType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('equiptype', models.ForeignKey(db_column='id_equiptype', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.tipoequipamento')),
                ('filter', models.ForeignKey(db_column='id_filter', on_delete=django.db.models.deletion.DO_NOTHING, to='filter.filter')),
            ],
            options={
                'db_table': 'filter_equiptype_xref',
                'abstract': False,
                'managed': True,
                'unique_together': {('filter', 'equiptype')},
            },
        ),
    ]
