# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.CharField(max_length=45, unique=True)),
                ('pwd', models.CharField(max_length=45)),
                ('id', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
                ('email', models.CharField(max_length=300)),
                ('user_ldap', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.AutoField(db_column='id_usuarios_do_grupo', primary_key=True, serialize=False)),
                ('ugrupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.ugrupo')),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
            options={
                'db_table': 'usuarios_do_grupo',
                'abstract': False,
                'managed': True,
                'unique_together': {('usuario', 'ugrupo')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(through='usuario.UsuarioGrupo', to='grupo.ugrupo'),
        ),
    ]
