# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vlan', '0001_initial'),
        ('equipamento', '0001_initial'),
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkIPv6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.IntegerField(db_column='bloco')),
                ('block1', models.CharField(db_column='bloco1', max_length=4)),
                ('block2', models.CharField(db_column='bloco2', max_length=4)),
                ('block3', models.CharField(db_column='bloco3', max_length=4)),
                ('block4', models.CharField(db_column='bloco4', max_length=4)),
                ('block5', models.CharField(db_column='bloco5', max_length=4)),
                ('block6', models.CharField(db_column='bloco6', max_length=4)),
                ('block7', models.CharField(db_column='bloco7', max_length=4)),
                ('block8', models.CharField(db_column='bloco8', max_length=4)),
                ('mask1', models.CharField(db_column='mask_bloco1', max_length=4)),
                ('mask2', models.CharField(db_column='mask_bloco2', max_length=4)),
                ('mask3', models.CharField(db_column='mask_bloco3', max_length=4)),
                ('mask4', models.CharField(db_column='mask_bloco4', max_length=4)),
                ('mask5', models.CharField(db_column='mask_bloco5', max_length=4)),
                ('mask6', models.CharField(db_column='mask_bloco6', max_length=4)),
                ('mask7', models.CharField(db_column='mask_bloco7', max_length=4)),
                ('mask8', models.CharField(db_column='mask_bloco8', max_length=4)),
                ('cluster_unit', models.CharField(db_column='cluster_unit', max_length=45, null=True)),
                ('active', models.BooleanField()),
                ('ambient_vip', models.ForeignKey(db_column='id_ambientevip', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.environmentvip')),
                ('network_type', models.ForeignKey(db_column='id_tipo_rede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vlan.tiporede')),
                ('vlan', models.ForeignKey(db_column='id_vlan', on_delete=django.db.models.deletion.DO_NOTHING, to='vlan.vlan')),
            ],
            options={
                'db_table': 'redeipv6',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NetworkIPv4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oct1', models.IntegerField(db_column='rede_oct1')),
                ('oct2', models.IntegerField(db_column='rede_oct2')),
                ('oct3', models.IntegerField(db_column='rede_oct3')),
                ('oct4', models.IntegerField(db_column='rede_oct4')),
                ('block', models.IntegerField(db_column='bloco')),
                ('mask_oct1', models.IntegerField(db_column='masc_oct1')),
                ('mask_oct2', models.IntegerField(db_column='masc_oct2')),
                ('mask_oct3', models.IntegerField(db_column='masc_oct3')),
                ('mask_oct4', models.IntegerField(db_column='masc_oct4')),
                ('broadcast', models.CharField(max_length=15)),
                ('cluster_unit', models.CharField(db_column='cluster_unit', max_length=45, null=True)),
                ('active', models.BooleanField()),
                ('ambient_vip', models.ForeignKey(db_column='id_ambientevip', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.environmentvip')),
                ('network_type', models.ForeignKey(db_column='id_tipo_rede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vlan.tiporede')),
                ('vlan', models.ForeignKey(db_column='id_vlan', on_delete=django.db.models.deletion.DO_NOTHING, to='vlan.vlan')),
            ],
            options={
                'db_table': 'redeipv4',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ipv6',
            fields=[
                ('id', models.AutoField(db_column='id_ipv6', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='descricao', max_length=100, null=True)),
                ('block1', models.CharField(db_column='bloco1', max_length=4)),
                ('block2', models.CharField(db_column='bloco2', max_length=4)),
                ('block3', models.CharField(db_column='bloco3', max_length=4)),
                ('block4', models.CharField(db_column='bloco4', max_length=4)),
                ('block5', models.CharField(db_column='bloco5', max_length=4)),
                ('block6', models.CharField(db_column='bloco6', max_length=4)),
                ('block7', models.CharField(db_column='bloco7', max_length=4)),
                ('block8', models.CharField(db_column='bloco8', max_length=4)),
                ('networkipv6', models.ForeignKey(db_column='id_redeipv6', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.networkipv6')),
            ],
            options={
                'db_table': 'ipsv6',
                'abstract': False,
                'managed': True,
                'unique_together': {('block1', 'block2', 'block3', 'block4', 'block5', 'block6', 'block7', 'block8', 'networkipv6')},
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(db_column='id_ip', primary_key=True, serialize=False)),
                ('oct4', models.IntegerField()),
                ('oct3', models.IntegerField()),
                ('oct2', models.IntegerField()),
                ('oct1', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('networkipv4', models.ForeignKey(db_column='id_redeipv4', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.networkipv4')),
            ],
            options={
                'db_table': 'ips',
                'abstract': False,
                'managed': True,
                'unique_together': {('oct1', 'oct2', 'oct3', 'oct4', 'networkipv4')},
            },
        ),
        migrations.CreateModel(
            name='Ipv6Equipament',
            fields=[
                ('id', models.AutoField(db_column='id_ipsv6_dos_equipamentos', primary_key=True, serialize=False)),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
                ('ip', models.ForeignKey(db_column='id_ipv6', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ipv6')),
            ],
            options={
                'db_table': 'ipsv6_dos_equipamentos',
                'abstract': False,
                'managed': True,
                'unique_together': {('ip', 'equipamento')},
            },
        ),
        migrations.CreateModel(
            name='IpEquipamento',
            fields=[
                ('id', models.AutoField(db_column='id_ips_dos_equipamentos', primary_key=True, serialize=False)),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
                ('ip', models.ForeignKey(db_column='id_ip', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ip')),
            ],
            options={
                'db_table': 'ips_dos_equipamentos',
                'abstract': False,
                'managed': True,
                'unique_together': {('ip', 'equipamento')},
            },
        ),
    ]
