# Generated by Django 4.2.4 on 2023-09-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roteiro', '__first__'),
        ('tipoacesso', '__first__'),
        ('ambiente', '__first__'),
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(db_column='id_equip', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('maintenance', models.BooleanField(db_column='maintenance')),
            ],
            options={
                'db_table': 'equipamentos',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marcas',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(db_column='id_modelo', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.marca')),
            ],
            options={
                'db_table': 'modelos',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_equipamento', primary_key=True, serialize=False)),
                ('tipo_equipamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_equipamento',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoGrupo',
            fields=[
                ('id', models.AutoField(db_column='id_equip_do_grupo', primary_key=True, serialize=False)),
                ('egrupo', models.ForeignKey(db_column='id_egrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='grupo.egrupo')),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'equip_do_grupo',
                'abstract': False,
                'managed': True,
                'unique_together': {('egrupo', 'equipamento')},
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='grupos',
            field=models.ManyToManyField(through='equipamento.EquipamentoGrupo', to='grupo.egrupo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.modelo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(db_column='id_tipo_equipamento', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.tipoequipamento'),
        ),
        migrations.CreateModel(
            name='ModeloRoteiro',
            fields=[
                ('id', models.AutoField(db_column='id_modelo_roteiro', primary_key=True, serialize=False)),
                ('modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.modelo')),
                ('roteiro', models.ForeignKey(db_column='id_roteiro', on_delete=django.db.models.deletion.DO_NOTHING, to='roteiro.roteiro')),
            ],
            options={
                'db_table': 'modelo_roteiro',
                'abstract': False,
                'managed': True,
                'unique_together': {('modelo', 'roteiro')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentControllerEnvironment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(db_column='id_environment', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('equipment', models.ForeignKey(db_column='id_equipment', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'equipment_controller_environment',
                'abstract': False,
                'managed': True,
                'unique_together': {('equipment', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='EquipamentoRoteiro',
            fields=[
                ('id', models.AutoField(db_column='id_equiptos_roteiros', primary_key=True, serialize=False)),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
                ('roteiro', models.ForeignKey(db_column='id_roteiros', on_delete=django.db.models.deletion.DO_NOTHING, to='roteiro.roteiro')),
            ],
            options={
                'db_table': 'equiptos_roteiros',
                'abstract': False,
                'managed': True,
                'unique_together': {('equipamento', 'roteiro')},
            },
        ),
        migrations.CreateModel(
            name='EquipamentoAmbiente',
            fields=[
                ('id', models.AutoField(db_column='id_equip_do_ambiente', primary_key=True, serialize=False)),
                ('is_router', models.BooleanField(db_column='is_router')),
                ('ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'equip_do_ambiente',
                'abstract': False,
                'managed': True,
                'unique_together': {('equipamento', 'ambiente')},
            },
        ),
        migrations.CreateModel(
            name='EquipamentoAcesso',
            fields=[
                ('id', models.AutoField(db_column='id_equiptos_access', primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(db_column='pass', max_length=20)),
                ('enable_pass', models.CharField(blank=True, max_length=20)),
                ('vrf', models.CharField(blank=True, db_column='id_vrf', max_length=100, null=True)),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
                ('tipo_acesso', models.ForeignKey(db_column='id_tipo_acesso', on_delete=django.db.models.deletion.DO_NOTHING, to='tipoacesso.tipoacesso')),
            ],
            options={
                'db_table': 'equiptos_access',
                'abstract': False,
                'managed': True,
                'unique_together': {('equipamento', 'tipo_acesso')},
            },
        ),
    ]
