# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(db_column='id_filter', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'filter',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
