# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPRelayIPv6',
            fields=[
                ('id', models.AutoField(db_column='id_dhcprelay_ipv6', primary_key=True, serialize=False)),
                ('ipv6', models.ForeignKey(db_column='id_ipv6', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ipv6')),
                ('networkipv6', models.ForeignKey(db_column='id_networkipv6', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.networkipv6')),
            ],
            options={
                'db_table': 'dhcprelay_ipv6',
                'abstract': False,
                'managed': True,
                'unique_together': {('ipv6', 'networkipv6')},
            },
        ),
        migrations.CreateModel(
            name='DHCPRelayIPv4',
            fields=[
                ('id', models.AutoField(db_column='id_dhcprelay_ipv4', primary_key=True, serialize=False)),
                ('ipv4', models.ForeignKey(db_column='id_ip', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ip')),
                ('networkipv4', models.ForeignKey(db_column='id_networkipv4', on_delete=django.db.models.deletion.DO_NOTHING, to='ip.networkipv4')),
            ],
            options={
                'db_table': 'dhcprelay_ipv4',
                'abstract': False,
                'managed': True,
                'unique_together': {('ipv4', 'networkipv4')},
            },
        ),
    ]
