# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(db_column='id_config', primary_key=True, serialize=False)),
                ('IPv4_MIN', models.SmallIntegerField(db_column='ip_v4_min')),
                ('IPv4_MAX', models.SmallIntegerField(db_column='ip_v4_max')),
                ('IPv6_MIN', models.SmallIntegerField(db_column='ip_v6_min')),
                ('IPv6_MAX', models.SmallIntegerField(db_column='ip_v6_max')),
            ],
            options={
                'db_table': 'config',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
