# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRede',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_rede', primary_key=True, serialize=False)),
                ('tipo_rede', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_rede',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(db_column='id_vlan', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('num_vlan', models.IntegerField()),
                ('ambiente', models.IntegerField(blank=True, db_column='id_ambiente', null=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('acl_file_name', models.CharField(blank=True, max_length=200)),
                ('acl_valida', models.BooleanField(default=False)),
                ('acl_file_name_v6', models.CharField(blank=True, max_length=200)),
                ('acl_valida_v6', models.BooleanField(default=False)),
                ('ativada', models.BooleanField(default=True)),
                ('vrf', models.CharField(db_column='vrf', max_length=100, null=True)),
                ('acl_draft', models.TextField(blank=True, db_column='acl_draft', null=True)),
                ('acl_draft_v6', models.TextField(blank=True, db_column='acl_draft_v6', null=True)),
                ('vxlan', models.BooleanField(blank=True, db_column='vxlan', default=False, null=True)),
            ],
            options={
                'db_table': 'vlans',
                'abstract': False,
                'managed': True,
                'unique_together': {('nome', 'ambiente'), ('num_vlan', 'ambiente')},
            },
        ),
    ]
