# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoPool',
            fields=[
                ('id', models.AutoField(db_column='id_opcaopool', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'opcoespool',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OptionPool',
            fields=[
                ('id', models.AutoField(db_column='id_optionspool', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('name', models.CharField(db_column='description', max_length=50)),
            ],
            options={
                'db_table': 'optionspool',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpcaoPoolAmbiente',
            fields=[
                ('id', models.AutoField(db_column='id_opcaopool_ambiente_xref', primary_key=True, serialize=False)),
                ('ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('opcao_pool', models.ForeignKey(db_column='id_opcaopool', on_delete=django.db.models.deletion.DO_NOTHING, to='api_pools.opcaopool')),
            ],
            options={
                'db_table': 'opcoespool_ambiente_xref',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OptionPoolEnvironment',
            fields=[
                ('id', models.AutoField(db_column='id_optionspool_environment_xref', primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(db_column='id_environment', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('option', models.ForeignKey(db_column='id_optionspool', on_delete=django.db.models.deletion.DO_NOTHING, to='api_pools.optionpool')),
            ],
            options={
                'db_table': 'optionspool_environment_xref',
                'abstract': False,
                'managed': True,
                'unique_together': {('option', 'environment')},
            },
        ),
    ]
