# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortChannel',
            fields=[
                ('id', models.AutoField(db_column='id_port_channel', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=10, unique=True)),
                ('lacp', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'port_channel',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoInterface',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_interface', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tipo_interface',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface', models.CharField(max_length=20, unique=True)),
                ('protegida', models.BooleanField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('id', models.AutoField(db_column='id_interface', primary_key=True, serialize=False)),
                ('vlan_nativa', models.CharField(blank=True, db_column='vlan_nativa', default=1, max_length=200, null=True)),
                ('channel', models.ForeignKey(blank=True, db_column='id_channel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interface.portchannel')),
                ('equipamento', models.ForeignKey(db_column='id_equip', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
                ('ligacao_back', models.ForeignKey(blank=True, db_column='id_ligacao_back', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interfaces_back', to='interface.interface')),
                ('ligacao_front', models.ForeignKey(blank=True, db_column='id_ligacao_front', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interfaces_front', to='interface.interface')),
                ('tipo', models.ForeignKey(blank=True, db_column='id_tipo_interface', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface.tipointerface')),
            ],
            options={
                'db_table': 'interfaces',
                'abstract': False,
                'managed': True,
                'unique_together': {('interface', 'equipamento')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentInterface',
            fields=[
                ('id', models.AutoField(db_column='id_int_ambiente', primary_key=True, serialize=False)),
                ('vlans', models.CharField(blank=True, max_length=200, null=True)),
                ('ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('interface', models.ForeignKey(db_column='id_interface', on_delete=django.db.models.deletion.DO_NOTHING, to='interface.interface')),
            ],
            options={
                'db_table': 'interface_do_ambiente',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
