# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asn',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'asn',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsnEquipment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('asn', models.ForeignKey(blank=True, db_column='id_asn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_asn.asn')),
                ('equipment', models.ForeignKey(blank=True, db_column='id_equipment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'asn_equipment',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
