# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(db_column='id_variable', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('value', models.CharField(db_column='value', max_length=50)),
                ('description', models.CharField(blank=True, db_column='description', max_length=100)),
            ],
            options={
                'db_table': 'variables',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
