# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('vpc', models.TextField(db_column='vpc_id', max_length=45)),
            ],
            options={
                'db_table': 'aws_vpc',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
