# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_acesso', primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'tipo_acesso',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
