# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
        ('api_route_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('route_map_in', models.ForeignKey(db_column='id_route_map_in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peergroup_route_map_in', to='api_route_map.routemap')),
                ('route_map_out', models.ForeignKey(db_column='id_route_map_out', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='peergroup_route_map_out', to='api_route_map.routemap')),
            ],
            options={
                'db_table': 'peer_group',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentPeerGroup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(db_column='id_environment', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('peer_group', models.ForeignKey(db_column='id_peer_group', on_delete=django.db.models.deletion.DO_NOTHING, to='api_peer_group.peergroup')),
            ],
            options={
                'db_table': 'environment_peer_group',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
