# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentListConfig',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(db_column='id_equipment', on_delete=django.db.models.deletion.DO_NOTHING, to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'equipment_list_config_bgp',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListConfigBGP',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('type', models.CharField(choices=[('P', 'P'), ('A', 'A'), ('C', 'C')], db_column='type', max_length=2)),
                ('config', models.TextField(db_column='config')),
                ('equipments', models.ManyToManyField(through='api_list_config_bgp.EquipmentListConfig', to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'list_config_bgp',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='equipmentlistconfig',
            name='list_config_bgp',
            field=models.ForeignKey(db_column='id_list_config_bgp', on_delete=django.db.models.deletion.DO_NOTHING, to='api_list_config_bgp.listconfigbgp'),
        ),
    ]
