# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisicaovips', '0001_initial'),
        ('ip', '0001_initial'),
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.BooleanField(db_column='created', default=False)),
                ('business', models.CharField(db_column='business', max_length=255, null=True)),
                ('service', models.CharField(db_column='service', max_length=255, null=True)),
                ('name', models.CharField(db_column='name', max_length=255, null=True)),
                ('environmentvip', models.ForeignKey(blank=True, db_column='id_environmentvip', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.environmentvip')),
                ('ipv4', models.ForeignKey(blank=True, db_column='id_ipv4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ip')),
                ('ipv6', models.ForeignKey(blank=True, db_column='id_ipv6', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ip.ipv6')),
            ],
            options={
                'db_table': 'vip_request',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipRequestPort',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('port', models.IntegerField(db_column='port')),
                ('identifier', models.CharField(db_column='identifier', max_length=255, null=True)),
                ('vip_request', models.ForeignKey(db_column='id_vip_request', on_delete=django.db.models.deletion.DO_NOTHING, to='api_vip_request.viprequest')),
            ],
            options={
                'db_table': 'vip_request_port',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipRequestPortPool',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('val_optionvip', models.CharField(blank=True, db_column='val_optionvip', max_length=255, null=True)),
                ('order', models.IntegerField(null=True)),
                ('optionvip', models.ForeignKey(db_column='id_opcoesvip', on_delete=django.db.models.deletion.DO_NOTHING, to='requisicaovips.optionvip')),
                ('server_pool', models.ForeignKey(db_column='id_server_pool', on_delete=django.db.models.deletion.DO_NOTHING, to='requisicaovips.serverpool')),
                ('vip_request_port', models.ForeignKey(db_column='id_vip_request_port', on_delete=django.db.models.deletion.DO_NOTHING, to='api_vip_request.viprequestport')),
            ],
            options={
                'db_table': 'vip_request_port_pool',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipRequestPortOptionVip',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('optionvip', models.ForeignKey(db_column='id_opcoesvip', on_delete=django.db.models.deletion.DO_NOTHING, to='requisicaovips.optionvip')),
                ('vip_request_port', models.ForeignKey(db_column='id_vip_request_port', on_delete=django.db.models.deletion.DO_NOTHING, to='api_vip_request.viprequestport')),
            ],
            options={
                'db_table': 'vip_request_port_optionsvip',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipRequestOptionVip',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('optionvip', models.ForeignKey(db_column='id_opcoesvip', on_delete=django.db.models.deletion.DO_NOTHING, to='requisicaovips.optionvip')),
                ('vip_request', models.ForeignKey(db_column='id_vip_request', on_delete=django.db.models.deletion.DO_NOTHING, to='api_vip_request.viprequest')),
            ],
            options={
                'db_table': 'vip_request_optionsvip',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VipRequestDSCP',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dscp', models.IntegerField(db_column='dscp')),
                ('vip_request', models.ForeignKey(db_column='id_vip_request', on_delete=django.db.models.deletion.DO_NOTHING, to='api_vip_request.viprequest')),
            ],
            options={
                'db_table': 'vip_request_dscp',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
