# Generated by Django 4.2.4 on 2023-09-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_peer_group', '0001_initial'),
        ('ip', '0001_initial'),
        ('api_asn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborV6',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('virtual_interface', models.CharField(db_column='virtual_interface', max_length=45)),
                ('created', models.BooleanField(db_column='created', default=False)),
                ('password', models.CharField(blank=True, db_column='password', max_length=45)),
                ('maximum_hops', models.CharField(db_column='maximum_hops', max_length=45)),
                ('timer_keepalive', models.CharField(db_column='timer_keepalive', max_length=45)),
                ('timer_timeout', models.CharField(db_column='timer_timeout', max_length=45)),
                ('description', models.CharField(db_column='description', max_length=45)),
                ('soft_reconfiguration', models.BooleanField(db_column='soft_reconfiguration', default=False)),
                ('community', models.BooleanField(db_column='community', default=False)),
                ('remove_private_as', models.BooleanField(db_column='remove_private_as', default=False)),
                ('next_hop_self', models.BooleanField(db_column='next_hop_self', default=False)),
                ('kind', models.CharField(choices=[('I', 'IBGP'), ('E', 'EBGP')], db_column='kind', max_length=2)),
                ('local_asn', models.ForeignKey(db_column='id_local_asn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv6_local_asn', to='api_asn.asn')),
                ('local_ip', models.ForeignKey(db_column='id_local_ip', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv6_local_ip', to='ip.ipv6')),
                ('peer_group', models.ForeignKey(db_column='id_peer_group', on_delete=django.db.models.deletion.DO_NOTHING, to='api_peer_group.peergroup')),
                ('remote_asn', models.ForeignKey(db_column='id_remote_asn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv6_remote_asn', to='api_asn.asn')),
                ('remote_ip', models.ForeignKey(db_column='id_remote_ip', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv6_remote_ip', to='ip.ipv6')),
            ],
            options={
                'db_table': 'neighbor_v6',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NeighborV4',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('virtual_interface', models.CharField(db_column='virtual_interface', max_length=45)),
                ('created', models.BooleanField(db_column='created', default=False)),
                ('password', models.CharField(blank=True, db_column='password', max_length=45)),
                ('maximum_hops', models.CharField(db_column='maximum_hops', max_length=45)),
                ('timer_keepalive', models.CharField(db_column='timer_keepalive', max_length=45)),
                ('timer_timeout', models.CharField(db_column='timer_timeout', max_length=45)),
                ('description', models.CharField(db_column='description', max_length=45)),
                ('soft_reconfiguration', models.BooleanField(db_column='soft_reconfiguration', default=False)),
                ('community', models.BooleanField(db_column='community', default=False)),
                ('remove_private_as', models.BooleanField(db_column='remove_private_as', default=False)),
                ('next_hop_self', models.BooleanField(db_column='next_hop_self', default=False)),
                ('kind', models.CharField(choices=[('I', 'IBGP'), ('E', 'EBGP')], db_column='kind', max_length=2)),
                ('local_asn', models.ForeignKey(db_column='id_local_asn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv4_local_asn', to='api_asn.asn')),
                ('local_ip', models.ForeignKey(db_column='id_local_ip', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv4_local_ip', to='ip.ip')),
                ('peer_group', models.ForeignKey(db_column='id_peer_group', on_delete=django.db.models.deletion.DO_NOTHING, to='api_peer_group.peergroup')),
                ('remote_asn', models.ForeignKey(db_column='id_remote_asn', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv4_remote_asn', to='api_asn.asn')),
                ('remote_ip', models.ForeignKey(db_column='id_remote_ip', on_delete=django.db.models.deletion.DO_NOTHING, related_name='neighborv4_remote_ip', to='ip.ip')),
            ],
            options={
                'db_table': 'neighbor_v4',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
