# Generated by Django 4.2.4 on 2023-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.AutoField(db_column='id_semaforo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'semaforo',
                'managed': False,
            },
        ),
    ]
