# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthcheck',
            fields=[
                ('id', models.AutoField(db_column='id_healthcheck', primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200)),
                ('healthcheck_type', models.CharField(max_length=45)),
                ('healthcheck_request', models.CharField(max_length=500)),
                ('healthcheck_expect', models.CharField(max_length=200)),
                ('destination', models.CharField(default='*:*', max_length=45)),
            ],
            options={
                'db_table': 'healthcheck',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthcheckExpect',
            fields=[
                ('id', models.AutoField(db_column='id_healthcheck_expect', primary_key=True, serialize=False)),
                ('expect_string', models.CharField(max_length=50)),
                ('match_list', models.CharField(max_length=50)),
                ('ambiente', models.ForeignKey(db_column='id_ambiente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
            ],
            options={
                'db_table': 'healthcheck_expect',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
