# Generated by Django 4.2.4 on 2023-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '__first__'),
        ('equipamento', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(db_column='id_dc', primary_key=True, serialize=False)),
                ('dcname', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'datacenter',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatacenterRooms',
            fields=[
                ('id', models.AutoField(db_column='id_dcroom', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('racks', models.IntegerField(blank=True, null=True)),
                ('spines', models.IntegerField(blank=True, null=True)),
                ('leafs', models.IntegerField(blank=True, null=True)),
                ('config', models.CharField(max_length=255)),
                ('dc', models.OneToOneField(db_column='id_dc', on_delete=django.db.models.deletion.DO_NOTHING, to='rack.datacenter')),
            ],
            options={
                'db_table': 'datacenterrooms',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(db_column='id_rack', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=4, unique=True)),
                ('mac_sw1', models.CharField(blank=True, db_column='mac_sw1', max_length=17, null=True)),
                ('mac_sw2', models.CharField(blank=True, db_column='mac_sw2', max_length=17, null=True)),
                ('mac_ilo', models.CharField(blank=True, db_column='mac_ilo', max_length=17, null=True)),
                ('config', models.BooleanField(default=False)),
                ('create_vlan_amb', models.BooleanField(default=False)),
                ('dcroom', models.ForeignKey(db_column='dcroom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rack.datacenterrooms')),
                ('id_ilo', models.ForeignKey(blank=True, db_column='id_equip3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamento_ilo', to='equipamento.equipamento')),
                ('id_sw1', models.ForeignKey(blank=True, db_column='id_equip1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamento_sw1', to='equipamento.equipamento')),
                ('id_sw2', models.ForeignKey(blank=True, db_column='id_equip2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamento_sw2', to='equipamento.equipamento')),
            ],
            options={
                'db_table': 'racks',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnvironmentRack',
            fields=[
                ('id', models.AutoField(db_column='id_ambienterack', primary_key=True, serialize=False)),
                ('ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='ambiente.ambiente')),
                ('rack', models.ForeignKey(db_column='id_rack', on_delete=django.db.models.deletion.DO_NOTHING, to='rack.rack')),
            ],
            options={
                'db_table': 'ambiente_rack',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
